### ISSUE TITLE
Python installation of development version

### ISSUE THREAD

**Issue by EskreisWinkler** [dfm/george#54]
I've been trying to get at this issue for a bit and haven't had any luck. The install of this version using "python setup.py install" gives me the following errors mostly involving reference to an "assemble_Matrix method"

Everything goes well until...

In file included from george/hodlr.cpp:476:
include/solver.h:59:9: warning: delete called on non-final 'george::HODLRSolverMatrix' that has virtual functions but non-virtual
      destructor [-Wdelete-non-virtual-dtor]
        delete matrix_;
        ^
include/solver.h:92:18: error: no matching member function for call to 'assemble_Matrix'
        solver_->assemble_Matrix(diag, tol_, 's', seed);
        ~~~~~~~~~^~~~~~~~~~~~~~~
./hodlr/header/HODLR_Tree.hpp:188:7: note: candidate function not viable: requires 3 arguments, but 4 were provided
        void assemble_Matrix(VectorXd& diagonal, double lowRankTolerance, char s) {
             ^
./hodlr/header/HODLR_Tree.hpp:73:7: note: candidate function not viable: requires single argument 'node', but 4 arguments were provided
        void assemble_Matrix(HODLR_Node<MatrixType>*& node) {
             ^
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by dfm** [comment]
Looks like you don't have the patched version of HODLR. How did you get the HODLR headers? Did you follow the directions here: http://dan.iel.fm/george/current/user/quickstart/#development-version

**Comment by EskreisWinkler** [comment]
I followed the install directions. All the HODLR repo's files were found in the hodlr folder. But it didn't seem like they were compiled by the initial install of george. Do I need to run additional install files inside of hodlr?

**Comment by dfm** [comment]
No. Try a fresh clone following the directions on that page. I just tried again and it works without any trouble. Let me know if you still have issues.

**Comment by EskreisWinkler** [comment]
Thank you for the feedback, it looks like the HODLRSolver works on its own.

I was surprised though, when I was re downloading that the install didn’t pass the tests from “nosetests -v george” when I ran it in my home directory. The following issue (even though in actually implementing a GP I encountered no issues) was reported:

Failure: ModuleNotFoundError (No module named 'george._kernels') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'george._kernels')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jonathaneskreis-winkler/george/george/__init__.py", line 13, in <module>
    from . import kernels
  File "/Users/jonathaneskreis-winkler/george/george/kernels.py", line 18, in <module>
    from ._kernels import CythonKernel
ModuleNotFoundError: No module named 'george._kernels'

----------------------------------------------------------------------
Ran 1 test in 0.757s

FAILED (errors=1)





On Feb 20, 2017, at 12:23 AM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


No. Try a fresh clone following the directions on that page. I just tried again and it works without any trouble. Let me know if you still have issues.

**Comment by dfm** [comment]
That happens if you run nose from within the source directory. If you want to do that then you need to run `python setup.py build_ext --inplace`
